### ISSUE TITLE
Not posible to load 32-bit FMU on 64 bit Windows

### ISSUE THREAD

**Issue by Nils12345678901234567** [Oaz/Femyou#4]
The library only tries to load 64-bit DLLs on 64 bit Windows, but it is possible to run both 32-bit and 64 bit code on Windows. The library should check if the current process is 32 bit or 64 bit

https://stackoverflow.com/a/1953411/1688642

```
if (IntPtr.Size == 4)
{
    // 32-bit
}
else if (IntPtr.Size == 8)
{
    // 64-bit
}
```

The issus is in the constructor of the Librarys class:
https://github.com/Oaz/Femyou/blob/56c94bbd6be2278770018817eb08b640d448dbc6/src/internal/Library.cs#L9

**Comment by Oaz** [comment]
Fixed.
 See [this commit](https://github.com/Oaz/Femyou/commit/e445b4a2d35b028f067457af3ae0951eb253e46b)

**Comment by Nils12345678901234567** [comment]
Excellent !
