### ISSUE TITLE
Get listed on the FMI tools page

### ISSUE THREAD

**Issue by chrbertsch** [Oaz/Femyou#7]
I would like to encourage you to get listed on the FMI tools page (https://fmi-standard.org/tools/), see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list how to create a pull request.

**Comment by Oaz** [comment]
Thank you for the suggestion!
[Pull request was created](https://github.com/modelica/fmi-standard.org/pull/647)
